// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSWu45LyM8gPb_tHvIKz73EC5nOC2Swk',
    appId: '1:962884237857:web:62b221a63ba4a68f3cc160',
    messagingSenderId: '962884237857',
    projectId: 'dumbbell-cartel-fd47c',
    authDomain: 'dumbbell-cartel-fd47c.firebaseapp.com',
    storageBucket: 'dumbbell-cartel-fd47c.firebasestorage.app',
    measurementId: 'G-GZ8XLW9K88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBBPKeGgwpVf46a2Tw5pz-T7HkGDf0cjU',
    appId: '1:962884237857:android:0df3345f81e907b63cc160',
    messagingSenderId: '962884237857',
    projectId: 'dumbbell-cartel-fd47c',
    storageBucket: 'dumbbell-cartel-fd47c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgedDS66mjMe9TKvslYBC9n0WpLChisVw',
    appId: '1:962884237857:ios:e6c56798d7eecb313cc160',
    messagingSenderId: '962884237857',
    projectId: 'dumbbell-cartel-fd47c',
    storageBucket: 'dumbbell-cartel-fd47c.firebasestorage.app',
    iosBundleId: 'com.example.dumbellCartel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgedDS66mjMe9TKvslYBC9n0WpLChisVw',
    appId: '1:962884237857:ios:e6c56798d7eecb313cc160',
    messagingSenderId: '962884237857',
    projectId: 'dumbbell-cartel-fd47c',
    storageBucket: 'dumbbell-cartel-fd47c.firebasestorage.app',
    iosBundleId: 'com.example.dumbellCartel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxSWu45LyM8gPb_tHvIKz73EC5nOC2Swk',
    appId: '1:962884237857:web:b9c652e571ed4a6e3cc160',
    messagingSenderId: '962884237857',
    projectId: 'dumbbell-cartel-fd47c',
    authDomain: 'dumbbell-cartel-fd47c.firebaseapp.com',
    storageBucket: 'dumbbell-cartel-fd47c.firebasestorage.app',
    measurementId: 'G-Q42SLDLEL6',
  );
}
